flex/app/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'app'

urlpatterns = [
    # front page
    url(r'^$', views.IndexView.as_view(), name='index'),

    # user registration
    url(r'^register/$', views.register, name='register'),

    # user login page
    url(r'^login/$', auth_views.login, {'template_name': 'app/login.html', 'redirect_authenticated_user': True}, name='login'),

    # user logout page
    url(r'^logout/$', auth_views.logout, {'template_name': 'app/logout.html'}, name='logout'),

    # individual models
    url(r'^profile/(?P<pk>[0-9]+)/$', views.ProfileView.as_view(), name='profile'),

    # view list of other user profiles
    url(r'^matches/$', views.MatchView.as_view(), name='matches'),

    # view users own profile
    url(r'^profile/$', views.profile, name='profile'),

    url(r'^matchSetting/(?P<pk>[0-9]+)/$', views.MatchSettingView.as_view(), name='matchSetting'),

    # edit User Profile url
    url(r'^profile/edit/$', views.edit_profile, name='edit-profile'),

    url(r'^connect/(?P<operation>.+)/(?P<pk>\d+)/$', views.update_match, name='update_match'),
]

flex/flex/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from flex.views import redirect_to_login
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    # root, redirect the user to login page
    url(r'^$', redirect_to_login, name='redirect_to_login'),
    url(r'^app/', include('app.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

flex/app/templates/app/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>FLEX</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="stylesheet" href="{% static 'app/style.css' %}">
    <link rel="stylesheet" href="{% static 'app/matches.css' %}">
    <link rel="stylesheet" href="{% static 'app/profile.css' %}">
    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" >

    <!-- Custom fonts for this template -->
    <link href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    <!-- Custom styles for this template -->
    <link href="{% static 'css/flex.min.css' %}" rel="stylesheet">
    <!-- Nav Bar -->
</head>

<body id="page-top" style="height:100%;">
        <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="container-fluid">
        <a class="navbar-brand js-scroll-trigger" href="{% url 'app:index' %}">Flex</a>
          {% if user.is_authenticated %}
        <a class="nav-link js-scroll-trigger" href="{%url 'app:matches'%}">Find Matches</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav navbar-right">
          <li class="nav-item dropdown" style="padding-right:50px;">
            <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><img id="user-image-thumb" src="{{request.user.userprofile.image_url}}"/> {{request.user.username}}</a>
            <div class="dropdown-menu" aria-labelledby="dropdown01">
              <a class="dropdown-item" href="/app/profile">View Profile</a>
              <a class="dropdown-item" href="{% url 'app:edit-profile'%}">Edit Profile</a>
              <a class="dropdown-item" href="#">Settings</a>
              <a class="dropdown-item" href="{% url 'app:logout'%}?next=/app/">Logout</a>
            </div>
          </li>
           {%else%}
              <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="{% url 'app:register'%}">Register</a>
              </li>
              <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="{% url 'app:login'%}">Login</a>
              </li>
              </ul>
          </ul>
            {%endif%}
        </div>
      </div>
    </nav>

        <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Plugin JavaScript -->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Contact Form JavaScript -->
    <script src="{% static 'js/jqBootstrapValidation.js' %}"></script>
    <script src="{% static 'js/contact_me.js' %}"></script>

    <!-- Custom scripts for this template -->
    <script src="{% static 'js/freelancer.min.js' %}"></script>
    {% block body %}
    {% endblock %}

        <!-- Footer -->
    <footer class="text-center" style="padding-top:100px;">
      <div class="footer-above">
        <div class="container">
          <div class="row">
            <div class="footer-col col-md-4">
              <h3></h3>
              <p>
                <br></p>
            </div>
            <div class="footer-col col-md-4">
              <h3>FLEX Web</h3>
              <ul class="list-inline">
                <li class="list-inline-item">
                  <a class="btn-social btn-outline" href="#">
                    <i class="fa fa-fw fa-facebook"></i>
                  </a>
                </li>
                <li class="list-inline-item">
                  <a class="btn-social btn-outline" href="#">
                    <i class="fa fa-fw fa-twitter"></i>
                  </a>
                </li>
                <li class="list-inline-item">
                  <a class="btn-social btn-outline" href="#">
                    <i class="fa fa-fw fa-linkedin"></i>
                  </a>
                </li>
                <li class="list-inline-item">
                  <a class="btn-social btn-outline" href="#">
                    <i class="fa fa-github"></i>
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="footer-below">
        <div class="container">
          <div class="row">
            <div class="col-lg-12">
              Copyright &copy; FLEX 2017
            </div>
          </div>
        </div>
      </div>
    </footer>
</body>
</html>

flex/app/templates/app/edit_profile_form.html
{% extends 'app/base.html' %}
{% load crispy_forms_tags %}
{% load crispy_forms_utils%}
{% load crispy_forms_field %}
{% load crispy_forms_filters %}
{%  block body %}
    <div  class="container">
        <div class="row">
            <div class="col-sm-12" style="font-size:20px;">
            <h2>Edit Profile Info</h2>
                <form method="post">
                    {% csrf_token %}
                    {% crispy form form.helper %} <!-- render using paragraph tags -->
                </form>
            </div>
        </div>
    </div>
{% endblock %}

flex/app/templates/app/index.html
<!-- user sign up/login  ability to enter username and password and ability to create the user
    login: username and password + login button
    signup: all user fields + signup button
-->
{% extends 'app/base.html' %}
{% block body %}
<body>
<div class="container">

      <!-- Jumbotron Header -->
      <header class="jumbotron jumbotron-fluid">
        <h4 class="display-3">Welcome to FLEX</h4>
        <p class="lead">A fitness based social network</p>
        <div>
          <img src="../../static/app/images/homepage-icon.png" style="width:100%; height:100%; margin:auto;">
        </div><br>
        {%if not user.is_authenticated%}
          <a href="{% url 'app:login'%}" class="btn btn-primary btn-lg">Sign Up Today!</a>
        {%endif%}
      </header>

      <!-- Page Features -->
      <div class="row text-center">
        <div class="col-lg-4 col-md-6 mb-4">
          <div class="card">
            <img src="../../static/app/images/get_connected.png" style="width:200px; height:200px; margin:auto;">
            <div class="card-body">
              <h4 class="card-title">Discover</h4>
              <p class="card-text">Discover others with similar interests</p>
            </div>
          </div>
        </div>
        <div class="col-lg-4 col-md-6 mb-4">
          <div class="card">
            <img src="../../static/app/images/events.png" style="width:200px; height:200px; margin:auto;" >
            <div class="card-body">
              <h4 class="card-title">Events</h4>
              <p class="card-text">Discover and join local fitness events around your area.</p>
            </div>
          </div>
        </div>

        <div class="col-lg-4 col-md-6 mb-4">
          <div class="card">
            <img src="../../static/app/images/forum.png" style="width:200px; height:200px; margin:auto;" >
            <div class="card-body">
              <h4 class="card-title">Fitness Advice</h4>
              <p class="card-text">Forum page where users can ask questions or look for advice</p>
            </div>
            <!--<div class="card-footer">-->
              <!--<a href="#" class="btn btn-primary">Find Out More!</a>-->
            <!--</div>-->
          </div>
        </div>

      </div>
      <!-- /.row -->

    </div>

    </div> <!-- /container -->

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>


</body>
{% endblock %}

flex/app/templates/app/login.html
{% extends 'app/base.html' %}
{%  block body %}
    <div  class="container">
        <h2>Log In to your FLEX account</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
        <button type="submit">Log in</button>
        </form>
    </div>
{%  endblock %}

flex/app/templates/app/logout.html
{% extends 'app/base.html' %}
{%  block body %}
    <div  class="container">
        <h2>Logged Out of FLEX</h2>
        </form>
    </div>
{%  endblock %}

flex/app/templates/app/matches.html
{% extends 'app/base.html' %}
{% load functions %}
{% block body %}
<style type="text/css">
img#profile-image{
    max-width: 400px;
    max-height: 400px;
}

#match_details{
    border: 1px #dedede solid;
    width: 600px;
    margin: auto;
    text-align: left;
    padding: 10px 15px;
    -moz-border-radius: 5px;
    border-radius: 5px;
    -moz-box-shadow: 0 0 3px #dfdfdf;
    -webkit-box-shadow: 0 0 3px #dfdfdf;
    box-shadow: 0 0 3px #dfdfdf;
}

#about
{
    width:600px;
    margin: auto;
    text-align: left;
    padding: 10px 15px;
    -moz-border-radius: 5px;
    border-radius: 5px;
}

.header {
    font-family: "Arial Black";
}

.match_card {
    font-size:20px;
    margin: 0 10px 75px;
    display: block;
    position: relative;
    top: 0;
    left: 0;
    width: 280px;
    height: 385px;
    border-radius: 3px;
    box-shadow: 0 1px 4px rgba(0,0,0,.1);
    background: #fff;
    opacity: 1;
    visibility: visible;
}

.image_wrapper{
    border-top-left-radius: 3px;
    border-top-right-radius: 3px;
    display: block;
    height: 215px;
    overflow: hidden;
    position: relative;
    width: 100%;
    z-index: 1;
    background-color: transparent;
    text-align: center;
    color: transparent;
}

.match_button{
    display: inline-block;
    border-radius: 4px;
    background-color: transparent;
    border: match;
    color: black;
    text-align: center;
    font-size: 14px;
    padding: 10px;
    width: 100px;
    transition: all 0.5s;
    cursor: pointer;
    margin: 5px;
}

.match_button:hover{
    background-color:green;
    color:white;
}

.un-match_button{
    display: inline-block;
    border-radius: 4px;
    background-color: green;
    border: none;
    color: #FFFFFF;
    text-align: center;
    font-size: 14px;
    padding: 10px;
    width: 100px;
    transition: all 0.5s;
    cursor: pointer;
    margin: 5px;
}
</style>
<body>
    {% if user_list %}
            <div class="container-fluid bg-3 text-center">
              <h1>Search for Matches</h1><br>
                  <div class="row">
                     {% for user in user_list %}
                        {%if not user.is_superuser%}
                            {% if request.user.userprofile.activities.all|intersect_activities:user.userprofile.activities.all|length >= 1%}
                      <div id="" class="col-sm-3">
                          <div class = "match_card">
                          <a class="image_link" href="{%url 'app:profile' user.id %}">
                          <span class="image_wrapper">
                              <img src="{{ user.userprofile.image_url }}" alt="profile_picture" style='height: 100%; width: 100%; object-fit: contain'>
                          </span>
                          </a>
                          <div class="match_card_text">
                              <div class="profile_info">
                                  <div class="username"><span class="username-text">
                              <a href="{%url 'app:profile' user.id %}" class="name">{{ user.username }}</a>
                          </span>
                          <span class="onlinedot username-online">
                          </span>
                      </div>
                          <div class="userinfo">
                              <span class="age">{{user.userprofile.user_age}}</span>
                              <span class="dot">· </span>
                              <span class="location">{{user.userprofile.address_city}}, CA</span></div>
                      </div>
                      <div class="percentages hide_on_hover">
                          <div class="percentage_wrapper match">
                              {% with mine=request.user.userprofile.activities.all|length %}
                                    {% with match=request.user.userprofile.activities.all|intersect_activities:user.userprofile.activities.all|length %}
                                        <span style = "color:red;" class="percentage">
                                            {{match|as_percentage_of:mine}}
                                        </span>
                                    {%endwith%}
                              {% endwith %}
                              <span>Match</span>
                          </div>
                          <div class="">
                          </div>
                      </div>
                              {%if user in matches %}
                                  <a href="{% url 'app:update_match' operation='remove' pk=user.pk%}">
                                      <button class="un-match_button">Remove</button>
                                  </a>
                              {%else%}
                                  <a  href="{% url 'app:update_match' operation='add' pk=user.pk%}">
                                      <button class="match_button">Favorite</button>
                                  </a>
                              {%endif%}
                            </div>
                          </div>
                      </div>
                            {%endif%}
                        {%endif%}
                    {% endfor %}
                  </div>
            </div>
    {% else %}
        <p>No users.</p>
    {% endif %}
</body>
{% endblock %}

flex/app/templates/app/other_profile.html
{% extends 'app/base.html' %}
{% block body %}
<style type="text/css">
    img{
        max-width: 400px;
        max-height: 400px;
    }

    #user-details {
        align:left;
    }

    .button {
      display: inline-block;
      border-radius: 4px;
      background-color: green;
      border: none;
      color: #FFFFFF;
      text-align: center;
      font-size: 14px;
      padding: 10px;
      width: 100px;
      transition: all 0.5s;
      cursor: pointer;
      margin: 5px;
    }
</style>
    <body>
        <div class="container">
            <div class="row">
                <div class="col-md-12 panel well">
                    <div class="col-md-3 col-md-offset-2" >
                        <img src="{{ user.userprofile.image_url }}"/>
                    </div>
                    <div class="col-md-4 col-md-offset-2">
                        <h1>{{ user }}</h1>
                        <h4>{{user.userprofile.user_age }} - {{ user.userprofile.address_city }}, CA</h4><br/>
                        <button class="button" style="vertical-align:middle">Message</button>
                        {%if user not in matches%}
                            <button class="button" style="vertical-align:middle">Favorite</button>
                        {%else%}
                            <button class="button" style="vertical-align:middle">Remove</button>
                        {%endif%}
                    </div>
                </div>
            </div>
              <div class="row">
                <div class="col-md-7">

                  <div class="row">
                    <div class="col-md-12 well">
                      <div class="panel panel-default text-left">
                        <div class="panel-body">
                          <p contenteditable="true">Status: Feeling Blue</p>
                          <button type="button" class="btn btn-default btn-sm">
                            <span class="glyphicon glyphicon-thumbs-up"></span> Like
                          </button>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div class="row">
                    <div class="col-md-12 well">
                      <div class="well">
                          <h3>About Me</h3>
                        <p>{{user.userprofile.bio}}</p>
                      </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-md-12 well">
                      <div class="well">
                          <h3>Goal</h3>
                        <p>{{user.userprofile.goal}}</p>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="col-md-3 col-md-offset-2 well">
                  <div class="well" id="user-details">
                    <strong><p>Details</p></strong>
                    <p>Weight: {{user.userprofile.weight}}</p>
                    <p>Height: {{user.userprofile.height}}</p>
                    <p>Body Type: {{user.userprofile.height}}</p>
                    <p>Gender: {{user.userprofile.gender}}</p>
                    <button class="btn btn-primary">Info</button>
                  </div>
                  <div class="well">
                    <strong><p>Interests</p></strong>
                    <p>
                        {% for activity in user.userprofile.activities.all %}
                            <span class="label label-primary">{{activity.name}}</span>
                        {% endfor %}
                    </p>
                  </div>
                </div>
              </div>
        </div>
    </body>
{% endblock %}

flex/app/templates/app/otherprofile.html
{% extends 'app/base.html' %}
{% block body %}
<style type="text/css">
    img{
        max-width: 400px;
        max-height: 400px;
    }

    #user-details {
        align:left;
    }

    .button {
      display: inline-block;
      border-radius: 4px;
      background-color: green;
      border: none;
      color: #FFFFFF;
      text-align: center;
      font-size: 14px;
      padding: 10px;
      width: 100px;
      transition: all 0.5s;
      cursor: pointer;
      margin: 5px;
    }
</style>
    <body>
        <div class="container">
            <div class="row">
                <div class="col-md-12 panel well">
                    <div class="col-md-3 col-md-offset-2" >
                        <img src="{{ user.userprofile.image_url }}"/>
                    </div>

                    <div class="col-md-4 col-md-offset-2">
                        <br/><br/><br/>
                        <h1>{{ user }}</h1>
                        <h4>{{user.userprofile.user_age }} - {{ user.userprofile.address_city }}, CA</h4><br/>
                        <button class="button" style="vertical-align:middle">Message</button>
                        <button class="button" style="vertical-align:middle">Like</button>
                    </div>
                </div>
            </div>
              <div class="row">
                <div class="col-md-7">

                  <div class="row">
                    <div class="col-md-12 well">
                      <div class="panel panel-default text-left">
                        <div class="panel-body">
                          <p contenteditable="true">Status: Feeling Blue</p>
                          <button type="button" class="btn btn-default btn-sm">
                            <span class="glyphicon glyphicon-thumbs-up"></span> Like
                          </button>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div class="row">
                    <div class="col-md-12 well">
                      <div class="well">
                          <h3>About Me</h3>
                        <p>Just Forgot that I had to mention something about someone to someone about how I forgot something, but now I forgot it. Ahh, forget it! Or wait. I remember.... no I don't.</p>
                      </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-md-12 well">
                      <div class="well">
                          <h3>Fitness Goals</h3>
                        <p>Just Forgot that I had to mention something about someone to someone about how I forgot something, but now I forgot it. Ahh, forget it! Or wait. I remember.... no I don't.</p>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="col-md-3 col-md-offset-2 well">
                  <div class="well" id="user-details">
                    <strong><p>Details</p></strong>
                    <p>Weight: {{user.userprofile.weight}}</p>
                    <p>Height: {{user.userprofile.height}}</p>
                    <p>Body Type: {{user.userprofile.height}}</p>
                    <p>Gender: {{user.userprofile.gender}}</p>
                    <button class="btn btn-primary">Info</button>
                  </div>
                  <div class="well">
                    <strong><p>Interests</p></strong>
                    <p>
                        {% for activity in user.userprofile.activities.all %}
                            <span class="label label-primary">{{activity.name}}</span>
                        {% endfor %}
                    </p>
                  </div>
                </div>
              </div>
        </div>
    </body>
{% endblock %}

flex/app/templates/app/profile.html
{% extends 'app/base.html' %}
{% block body %}
<style type="text/css">
    img{
        max-width: 400px;
        max-height: 400px;
    }

    #user-details {
        align:left;
    }

    .matches_list img {
        width:40px;
        height:40px;
        border-radius:50%;
    }
</style>
    <body>
        <div class="container">
            <div class="row">
                <div class="col-md-12 panel well">
                    <div class="col-md-3 col-md-offset-2" >
                        <img src="{{ user.userprofile.image_url }}"/>
                    </div>

                    <div class="col-md-4 col-md-offset-2">
                        <br/><br/><br/>
                        <h1>{{ user }}</h1>
                        <h4>{{user.userprofile.user_age }} - {{ user.userprofile.address_city }}, CA</h4><br/>
                    </div>
                </div>
            </div>
              <div class="row">
                <div class="col-md-7">
                  <div class="row">
                    <div class="col-md-12 well">
                      <div class="panel panel-default text-left">
                        <div class="panel-body">
                          <p contenteditable="true">Status: Feeling Blue</p>
                          <button type="button" class="btn btn-default btn-sm">
                            <span class="glyphicon glyphicon-pencil"></span> Update
                          </button>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-md-12 well">
                      <div class="well">
                          <h3>About Me</h3>
                        <p>{{user.userprofile.bio}}</p>
                      </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-md-12 well">
                      <div class="well">
                          <h3>Goal</h3>
                        <p>{{user.userprofile.goal}}</p>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="col-md-3 col-md-offset-2 well">
                  <div class="well" id="user-details">
                    <strong><p>Details</p></strong>
                    <p>Weight: {{user.userprofile.weight}}</p>
                    <p>Height: {{user.userprofile.height}}</p>
                    <p>Gender: {{user.userprofile.gender}}</p>
                    <button class="btn btn-primary">Info</button>
                  </div>
                  <div class="well">
                    <strong><p>Interests</p></strong>
                    <p>
                        {% for activity in user.userprofile.activities.all %}
                            <span class="label label-primary">{{activity.name}}</span>
                        {% endfor %}
                    </p>
                  </div>
                  <div class="well">
                    <strong><p>You Liked</p></strong>
                    <p class="matches_list">
                        {% for match in matches %}
                            <a href="{% url 'app:profile' match.id %}">
                                <img src="{{ match.userprofile.image_url }}"></img> <strong>{{match}}</strong><br>
                            </a>
                        {% endfor %}
                    </p>
                  </div>
                </div>
              </div>
        </div>
    </body>
{% endblock %}

flex/app/templates/app/registration_form.html
{% extends 'app/base.html' %}
{%  block body %}
<style type="text/css">
    .errorlist
    {
        color:red;
    }
</style>
    <div  class="container">
        <h2>FLEX Registration</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }} <!-- render using paragraph tags -->
        <button type="submit">Register</button>
        </form>
    </div>
{% endblock %}

flex/app/templates/app/user.html
{% extends 'app/base.html' %}
{% block body %}
    <style type="text/css">
        img {
            max-width: 300px;
            max_height:300px;
        }
    </style>
    <h1>{{ profile.first_name }} {{ profile.last_name }}</h1>
    <img src = "{{ profile.image_url }}"/>
    <h3>Bio: </h3>
    <span>{{ profile.bio}}</span>
    <h3>Activities: </h3>
    {% for activity in profile.activities.all %}
        <span>{{ activity.name }}</span><br/>
    {% endfor %}
    <h3>Goals:</h3>
    {% for goal in profile.goals.all %}
        <span>{{ goal.name }}</span>
    {% endfor %}
{% endblock %}

flex/app/templates/app/userprofile_form.html
{% extends 'app/base.html' %}
{%  block body %}
    <div  class="container">
        <h2>Edit Profile Info</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }} <!-- render using paragraph tags -->
        <button type="submit">Update</button>
        </form>
    </div>
{% endblock %}